source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0


target 'RBSWorldIPad', :exclusive => true do

  pod 'AsyncDisplayKit'

  pod 'Reveal-iOS-SDK'
  pod 'pop'
  pod 'SDWebImage'

  pod 'Regexer'
  pod 'AFNetworking'
  pod 'ISMemoryCache'
  pod 'XMLDictionary'
  pod 'Bolts'


  # ________________collect common library___________________
  pod "IOS_Collection_Code", :path => "../dependencies/collect/IOS_Collection_Code"

  # ________________Project layers___________________
  pod "Business-Logic-Layer", :path => "../dependencies/layers/Business-Logic-Layer"

  # ________________Projects for iPad___________________
  pod "YouTubeAPI3-Objective-C-wrapper", :path => "../dependencies/lib/YouTubeAPI3-Objective-C-wrapper"
  pod "YKMediaPlayerKit", :path => "../dependencies/lib/YKMediaPlayerKit"
  pod "google-api-services-youtube", :path => "../dependencies/layers/google-api-services-youtube"
  pod "MPMoviePlayerController-Subtitles", :path => "../dependencies/lib/MPMoviePlayerController-Subtitles"

  # ________________module Projects___________________
  pod "UI_Login_Layer", :path => "../dependencies/layers/UI_Login_Layer"

end

target 'RBSWorldIPadTests', :exclusive => true do

  # pod 'OCMockito', '~> 1.0'

  #pod 'OCHamcrest', :path => '/Volumes/Home/wanghaogithub720/cocoapods/Cocoapods_Libraries/OCHamcrest'
  #pod 'OCMockito', :path => '/Volumes/Home/wanghaogithub720/cocoapods/Cocoapods_Libraries/OCMockito'


end
