source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0
inhibit_all_warnings!

def import_pods
  pod 'Google-API-Client'
  pod "YouTubeAPI3-Objective-C-wrapper", :path => "../dependencies/lib/YouTubeAPI3-Objective-C-wrapper"
  pod "google-api-services-youtube", :path => "../dependencies/layers/google-api-services-youtube"

  pod 'AFNetworking'
  pod 'XMLDictionary'
  pod 'Regexer'

end

target 'RBSWorldIPad', :exclusive => true do
  import_pods

# ________________TestFlight library___________________

# ________________collect common library___________________
  pod "IOS_Collection_Code", :path => "../dependencies/collect/IOS_Collection_Code"


  pod 'AsyncDisplayKit'
  pod 'Reveal-iOS-SDK'
  pod 'pop'
  pod 'SDWebImage'

  pod 'ISMemoryCache'
  pod 'Bolts'
  pod 'TPKeyboardAvoiding'

# ________________Project layers___________________
  pod "Business-Logic-Layer", :path => "../dependencies/layers/Business-Logic-Layer"

# ________________Projects for iPad___________________
  pod "YKMediaPlayerKit", :path => "../dependencies/lib/YKMediaPlayerKit"
  pod "MPMoviePlayerController-Subtitles", :path => "../dependencies/lib/MPMoviePlayerController-Subtitles"

# ________________module Projects___________________
  pod "UI_Login_Layer", :path => "../dependencies/layers/UI_Login_Layer"
  pod "UI_VideoTable_Layer", :path => "../dependencies/layers/UI_VideoTable_Layer"


end

target 'RBSWorldIPadTests', :exclusive => true do
  pod 'Expecta'
  # pod 'kiwi'

  import_pods
end
